tutoringApp/chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"
urlpatterns = [
    path("tutor/<int:tutor_id>/", view=views.TutorChatView.as_view(), name="tutor_chat"),
    path("tutor/<int:tutor_id>/<int:student_id>/", view=views.TutorChatWindowView.as_view(), name="tutor_chat_window"),
    path("student/<int:student_id>/", view=views.StudentChatView.as_view(), name="student_chat"),
    path("student/<int:tutor_id>/<int:student_id>/", view=views.StudentChatWindowView.as_view(), name="student_chat_window"),
]

tutoringApp/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path("", view=views.homeView, name="home")
]

tutoringApp/lessons/urls.py
from django.urls import path

from lessons import views

app_name = "lessons"
api_endpoints = [
    path(
        "solution/create",
        view=views.SolutionAPIView.as_view(),
        name="solution_create",
    ),
    path(
        "solution/delete/<int:pk>",
        view=views.SolutionAPIView.as_view(),
        name="solution_delete",
    ),
    path(
        "task/update/<int:pk>",
        view=views.TaskAPIView.as_view(),
        name="task_update",
    ),
    path(
        "absence/update/<int:pk>",
        view=views.update_lesson_absence_view,
        name="lesson_update_absence",
    ),
]
urlpatterns = [
    path(
        "booking/create/<int:availability_id>",
        view=views.create_booking_view,
        name="booking_create",
    ),
    path(
        "booking/display/student",
        view=views.BookingsDisplay4Student.as_view(),
        name="booking_display_student",
    ),
    path(
        "booking/display/tutor",
        view=views.BookingsDisplay4Tutor.as_view(),
        name="booking_display_tutor",
    ),
    path(
        "booking/delete/<int:pk>",
        view=views.BookingDeleteView.as_view(),
        name="booking_delete",
    ),
    path(
        "update/<int:pk>",
        view=views.UpdateLessonView.as_view(),
        name="lesson_update",
    ),
    path(
        "task/delete/<int:task_id>",
        view=views.delete_task_view,
        name="task_delete",
    ),
    path(
        "material/delete/<int:material_id>",
        view=views.delete_material_view,
        name="material_delete",
    ),
    path(
        "student/<int:pk>",
        view=views.DisplayLessonStudentView.as_view(),
        name="lesson_display_student",
    ),
    path(
        "tutor/<int:pk>",
        view=views.DisplayLessonTutorView.as_view(),
        name="lesson_display_tutor",
    ),
] + api_endpoints

tutoringApp/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"
urlpatterns = [
    path("login/", view=views.LoginView.as_view(), name="login"),
    path("logout/", view=views.logout_view, name="logout"),
    path("register/", view=views.RegisterView.as_view(), name="register"),
    path("create/<int:user_id>", view=views.create_profile_view, name="create"),
    path(
        "student/update/<int:pk>",
        view=views.UpdateStudentProfileView.as_view(),
        name="student_update",
    ),
    path(
        "tutor/update/<int:pk>",
        view=views.UpdateTutorProfileView.as_view(),
        name="tutor_update",
    ),
    path(
        "student/<int:pk>",
        view=views.DisplayStudentProfileView.as_view(),
        name="student_display",
    ),
    path(
        "tutor/<int:pk>",
        view=views.DisplayTutorProfileView.as_view(),
        name="tutor_display",
    ),
    path(
        "password_change",
        view=views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset",
        view=views.ProfilesPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        view=views.ProfilesPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.ProfilesPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.ProfilesPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

tutoringApp/search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path("student", view=views.StudentSearchResultsView.as_view(), name="for_student"),
    path("tutor", view=views.TutorSearchResultsView.as_view(), name="for_tutor"),
]

tutoringApp/tutoringApp/urls.py
"""URL configuration for tutoringApp project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("profiles/", include("profiles.urls")),
    path("tutors/", include("tutors.urls")),
    path("lessons/", include("lessons.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    path("search/", include("search.urls")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutoringApp/templates/tutoringApp/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
                TutoringApp
            {% endblock %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'tutoringApp/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'tutoringApp/css/generals.css' %}">
        <link rel="stylesheet" href="{% static 'tutoringApp/css/header_general.css' %}">
        {% block styles %}
        {% endblock %}

        {% block styles_additional %}
        {% endblock %}

        <script defer src="{% static 'tutoringApp/js/getCookie.js' %}"></script>
        {% block script %}
        {% endblock %}

        {% block script_search %}
        {% endblock %}
    </head>
    <body>
        <header>
            <div class="header-left header-side">
                <div class="header-left-logo">
                    <a href="{% url 'home:home' %}">
                        <h2>
                            TutorApp
                        </h2>
                    </a>
                </div>

            {% block search %}
            {% endblock %}
                
            </div>
            <div class="header-right header-side">
                {% if user.is_authenticated %}
                    <input type="checkbox" class="header-right-checkbox" id="header-right-checkbox">
                    <div class="header-right-username link-container">
                        <a href="#">
                            {{ user.username }}
                        </a>
                    </div>
                    <div class="header-right-profile">
                        <img src="{{profile_pic_url}}">
                    </div>
                    <label for="header-right-checkbox">
                        <div class="header-right-arrow icon_green">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </div>
                    </label>
                    <div class="header-right-dropdown">
                        {% block header_links %}
                        {% endblock %}
                        <div class="header-right-dropdown-log_out header-right-dropdown-item">
                            <a href="{% url 'profiles:logout' %}">
                                Log out
                            </a>
                        </div>
                    </div>
                {% else %} 
                    <a href="{% url 'profiles:login' %}">
                        <div class="header-right-log_in adjacent-container">
                            <div class="header-right-log_in-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                </svg>
                            </div>
                            <div class="header-right-log_in-text">
                                Log in 
                            </div>
                        </div>
                    </a>
                {% endif %}
            </div>
        </header>
        
        <main>
            {% block main %}
            {% endblock %}
        </main>

        <div class="info">
            {% block info %}
            {% endblock %}
        </div>
        
        <footer>
        </footer>
    </body>
</html>

tutoringApp/templates/tutoringApp/base_header_clean.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
            {% endblock %}
        </title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'tutoringApp/css/base.css' %}">
        <link rel="stylesheet" href="{% static 'tutoringApp/css/generals.css' %}">
        <link rel="stylesheet" href="{% static 'tutoringApp/css/header_general.css' %}">
        {% block styles %}
        {% endblock %}

        {% block script %}
        {% endblock %}
    </head>
    <body>
        <header>
            <div class="header-left header-side">
                <div class="header-left-logo">
                    <a href="{% url 'home:home' %}">
                        <h2>
                            TutorApp
                        </h2>
                    </a>
                </div>    
            </div>
            <div class="header-right header-side"></div>
        </header>
        
        <main>
            {% block main %}
            {% endblock %}
        </main>

        <footer>
        </footer>
    </body>
</html>

tutoringApp/templates/tutoringApp/base_student.html
{% extends 'tutoringApp/base.html' %}

{% block script_search %}
    {% load static %}
    <script defer src="{% static 'tutoringApp/js/searchStudent.js' %}"></script>
{% endblock %}

{% block search %}
<div class="mobile header-left-search header-side-item_mobile">
    <div class="header-left-search-icon">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
    </div>
</div>
<div class="desktop header-left-search header-side-item_desktop">
    <select class="header-left-search-subject" id="header-left-search-subject">
        {% for subject in subjects %}
            <option value="{{subject.pk}}">{{subject.name}}</option>
        {% endfor %}
    </select>
    <input type="text" class="header-left-search-first_name" id="header-left-search-first_name" placeholder="First name">
    <input type="text" class="header-left-search-last_name" id="header-left-search-last_name" placeholder="Last name">
    <button class="header-left-search-button" id="header-left-search-button">
        <a href="{% url 'search:for_student' %}">
            <div class="header-left-search-button-icon">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
            </div>
        </a>
    </button>  
</div>
{% endblock %}

{% block header_links %}
<div class="header-right-dropdown-item">
    <a href="{% url 'profiles:student_display' user.id %}">
        Profile
    </a>
</div>  
<div class="header-right-dropdown-item">
    <a href="{% url 'lessons:booking_display_student' %}">
        Lessons
    </a>
</div>
<div class="header-right-dropdown-item">
    <a href="{% url 'subscriptions:learning_student_list' %}">
        Subscriptions
    </a>
</div>
<div class="header-right-dropdown-item">
    <a href="{% url 'chat:student_chat' user.id %}">
        Chats
    </a>
</div>
{% endblock %}

tutoringApp/templates/tutoringApp/base_tutor.html
{% extends 'tutoringApp/base.html' %}
       
{% block styles_additional %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'tutoringApp/css/base_tutor.css' %}">
{% endblock %}

{% block script_search %}
    {% load static %}
    <script defer src="{% static 'tutoringApp/js/searchTutor.js' %}"></script>
{% endblock %}

{% block search %}
<div class="mobile header-left-search header-side-item_mobile">
    <div class="header-left-search-icon">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
        </svg>
    </div>
</div>
<div class="desktop header-left-search header-side-item_desktop">
    <input type="text" class="header-left-search-first_name" id="header-left-search-first_name" placeholder="First name">
    <input type="text" class="header-left-search-last_name" id="header-left-search-last_name" placeholder="Last name">
    <button class="header-left-search-button" id="header-left-search-button">
        <a href="{% url 'search:for_tutor' %}">
            <div class="header-left-search-button-icon">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
            </div>
        </a>
    </button>  
</div>
{% endblock %}

{% block header_links %}
<div class="header-right-dropdown-item">
    <a href="{% url 'profiles:tutor_display' user.id %}">
        Profile
    </a>
</div>  
<div class="header-right-dropdown-item">
    <a href="{% url 'lessons:booking_display_tutor'%}">
        Lessons
    </a>
</div>
<div class="header-right-dropdown-item">
    <a href="{% url 'subscriptions:learning_tutor_list' %}">
        Subscriptions
    </a>
</div>
<div class="header-right-dropdown-item">
    <a href="{% url 'chat:tutor_chat' user.id %}">
        Chats
    </a>
</div>
{% endblock %}

tutoringApp/templates/tutoringApp/forbidden.html
{% extends 'tutoringApp/base_header_clean.html' %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'tutoringApp/css/forbidden.css' %}">
{% endblock %}

{% block main %}
    <div class="forbidden box">
        <div class="forbidden-header box-header">
            Warning
        </div>
        <div class="forbidden-main box-main_padded stack_container">
            <div class="forbidden-main-warning_message">
                {{warning_message}}
            </div>
            <div class="forbidden-main-redirect-link centered_button_container">
                <div class="forbidden-main-redirect-link button_fill_red">
                    <a href="{{redirect_link}}">
                        Go to {{redirect_destination}}.
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}