tutoringApp/chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"
urlpatterns = [
    path("tutor/<int:tutor_id>/", view=views.TutorChatView.as_view(), name="tutor_chat"),
    path("tutor/<int:tutor_id>/<int:student_id>/", view=views.TutorChatWindowView.as_view(), name="tutor_chat_window"),
    path("student/<int:student_id>/", view=views.StudentChatView.as_view(), name="student_chat"),
    path("student/<int:tutor_id>/<int:student_id>/", view=views.StudentChatWindowView.as_view(), name="student_chat_window"),
]

tutoringApp/profiles/urls.py
from django.urls import path

from . import views

app_name = "profiles"
urlpatterns = [
    path("login/", view=views.LoginView.as_view(), name="login"),
    path("logout/", view=views.logout_view, name="logout"),
    path("register/", view=views.RegisterView.as_view(), name="register"),
    path("create/<int:user_id>", view=views.create_profile_view, name="create"),
    path(
        "student/update/<int:pk>",
        view=views.UpdateStudentProfileView.as_view(),
        name="student_update",
    ),
    path(
        "tutor/update/<int:pk>",
        view=views.UpdateTutorProfileView.as_view(),
        name="tutor_update",
    ),
    path(
        "student/<int:pk>",
        view=views.DisplayStudentProfileView.as_view(),
        name="student_display",
    ),
    path(
        "tutor/<int:pk>",
        view=views.DisplayTutorProfileView.as_view(),
        name="tutor_display",
    ),
    path(
        "password_change",
        view=views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset",
        view=views.ProfilesPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        view=views.ProfilesPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.ProfilesPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.ProfilesPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

tutoringApp/tutoringApp/urls.py
"""URL configuration for tutoringApp project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("profiles/", include("profiles.urls")),
    path("tutors/", include("tutors.urls")),
    path("lessons/", include("lessons.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    path("search/", include("search.urls")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutoringApp/tutors/urls.py
"""URL configuration for tutoringApp project."""

from django.urls import path

from . import views

app_name = "tutors"
api_endpoints = [
    path(
        "availability/delete/<int:pk>",
        view=views.AvailabilityAPIView.as_view(),
        name="availability_delete",
    ),
    path(
        "availability/create",
        view=views.AvailabilityAPIView.as_view(),
        name="availability_create",
    ),
    path(
        "availability/update",
        view=views.AvailabilityAPIView.as_view(),
        name="availability_update",
    ),
]
urlpatterns = [
    path(
        "availability/<int:pk>/<int:month>/<int:year>",
        view=views.AvailabilityInputView.as_view(),
        name="availability",
    ),
    path(
        "services/<int:pk>",
        view=views.ServiceConfigurationView.as_view(),
        name="services",
    ),
    path(
        "service/delete/<int:service_id>",
        view=views.service_delete_view,
        name="service_delete",
    ),
] + api_endpoints

tutoringApp/profiles/views/tutor.py
from logging import getLogger
from typing import Any, Literal, Optional, Union

from django.conf import settings
from django.forms.models import BaseInlineFormSet, BaseModelForm
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy

from profiles.forms import profile_language_list_formset, subject_formset
from profiles.models import ProfileLanguageList, Service

from .profile import UpdateProfileView

LOGGER = getLogger(__name__)


class UpdateTutorProfileView(UpdateProfileView):
    template_name = "profiles/update_tutor.html"
    subject_formset_errors = False
    profile_language_formset_errors = False

    def form_valid(
        self, form: BaseModelForm
    ) -> Union[HttpResponse, HttpResponseRedirect]:
        """Check valididty of the main form and additional formsets.

        The method checks if the main form and
        any other form rendered on the page is valid.
        If so, the user gets redirected further to the page
        whos URL is returned by the self.get_success_url method.
        In any other case the user is redirected back to the
        profile update page and the error messages are getting
        displayed.

        Args:
            form: An instance of the form class
                    (the class is specified in the
                    self.get_form_class method)
                    with data provided by the user.
        Returns:
            HttpResponse if all forms are valid, HttpResponseRedirect
            otherwise.
        """
        self._save_education_data()
        self._save_formset_data(
            profile_language_list_formset, "profile_language_formset_errors"
        )
        self._save_formset_data(subject_formset, "subject_formset_errors")
        self._save_user_data()

        if not self._additional_forms_have_errors():
            LOGGER.debug(
                "Profile of user %(username)s with id %(id)s successfuly updated.",
                {"username": self.request.user.username, "id": self.request.user.id},
            )
            return super().form_valid(form)
        return HttpResponseRedirect(
            reverse_lazy("profiles:tutor_update", kwargs={"pk": self.kwargs["pk"]})
        )

    def get_context_data(self, **kwargs):
        """Add formsets and other necessary info to default context."""
        context = super().get_context_data(**kwargs)

        context["subject_formset"] = subject_formset(instance=self.get_object())
        context["profile_language_list_formset"] = profile_language_list_formset(
            instance=self.get_object()
        )

        context["profile_language_formset_errors"] = self._check_for_formset_error(
            "profile_language_formset_errors"
        )
        context["subject_formset_errors"] = self._check_for_formset_error(
            "subject_formset_errors"
        )

        context["currency"] = settings.CURRENCY

        context["subject_objects_in_db"] = len(
            Service.objects.filter(tutor=self.get_object())
        )
        context["profile_language_list_objects_in_db"] = len(
            ProfileLanguageList.objects.filter(profile=self.get_object())
        )

        return context

    def _additional_forms_have_errors(self) -> bool:
        """Check if any of the additional forms have errors.

        The method extends the results of the implementation
        in the base class (UpdateProfileView) by also checking
        for errors in formsets specific to updating Tutor's profile.

        Returns:
            Boolean info indicating any errors
            with additional forms added manually to the
            context.
        """
        error_info = super()._additional_forms_have_errors()
        return any(
            [
                error_info,
                self.subject_formset_errors,
                self.profile_language_formset_errors,
            ]
        )

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        """Ensure correct update page is displayed according to Profile's type."""
        requested_profile = self.model.objects.get(pk=self.kwargs["pk"])
        if requested_profile.is_student():
            return HttpResponseRedirect(
                reverse_lazy(
                    "profiles:student_update", kwargs={"pk": self.kwargs["pk"]}
                )
            )
        return super().get(request, *args, **kwargs)

    def _save_formset_data(
        self,
        formset_class: type[BaseInlineFormSet],
        error_session_key: Literal[
            "profile_language_formset_errors", "subject_formset_errors"
        ],
    ) -> None:
        """Save data provided via formset.

        The method validates the formset and if there
        are no issues detected, the data gets saved
        and the user is taken to the next page whos
        URL is returned by self.get_success_url method.
        If any errors are spotted when validating the
        formset, the list of error messages gets
        added to session info and the value of
        an appropriate flag is set to True to mark that
        further error 'handling' is needed.

        Args:
            formset_class: An instance of the formset
                            that the data was originally
                            send in.
            error_session_key: The key that the error list
                                will be assigned to in the
                                session object. The value of this
                                argument will also allow to
                                decide which flag (class's attribute)
                                will be set to True in case of errors.
        """
        filled_formset = formset_class(self.request.POST, instance=self.get_object())
        if filled_formset.is_valid():
            filled_formset.save()
        else:
            self.request.session[error_session_key] = filled_formset.errors

            if error_session_key == "profile_language_formset_errors":
                self.profile_language_formset_errors = True
            elif error_session_key == "subject_formset_errors":
                self.subject_formset_errors = True

            LOGGER.warning(
                "%(formset)s uploaded by %(username)s with id %(id)s contains errors: %(errors)s"
                % {
                    "formset": formset_class.__name__,
                    "username": self.request.user.username,
                    "id": self.request.user.id,
                    "errors": filled_formset.errors,
                }
            )

    def _check_for_formset_error(
        self,
        error_session_key: Literal[
            "profile_language_formset_errors", "subject_formset_errors"
        ],
    ) -> Optional[list[dict[str, str]]]:
        """Check if error messages are present in session info.

        Args:
            error_session_key: Key with the error name to be
                                searched for in the session
                                object.

        Returns:
            If error messages are present, the list containing
            them gets returned and the value is removed from the session.
            In other case, None is returned.
        """
        if self.request.session.get(error_session_key):
            formset_errors = self.request.session.get(error_session_key)
            del self.request.session[error_session_key]
            return formset_errors

tutoringApp/search/views/tutor.py
"""View for generating search results for Tutors."""
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.functions import Lower
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic.list import ListView

from profiles.forms import AccountType
from profiles.models import Profile


class TutorSearchResultsView(ListView, LoginRequiredMixin):
    """View for generating search results for Tutors."""

    model = Profile
    paginate_by = 10
    template_name = r"search\tutor.html"

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Ensure that correct page for given account type is displayed.

        In case that the logged in user is a Student, they get redirected to
        a page with search results for Students while preserving the query
        parameters provided in the initial request.
        """
        if request.session.get("account_type") == AccountType.STUDENT.value:
            return HttpResponseRedirect(request.get_full_path_info().replace("tutor", "student"))
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> QuerySet[Profile]:
        """Filter the search results based on query parameters."""
        search_first_name = self.request.GET.get("first_name", None)
        search_last_name = self.request.GET.get("last_name", None)
        students = (
            Profile.objects.annotate(
                first_name_lower=Lower("user__first_name"), last_name_lower=Lower("user__last_name")
            )
            .filter(teaching_since__isnull=True)
            .distinct()
        )
        if search_first_name:
            students = students.filter(first_name_lower__contains=search_first_name.lower())
        if search_last_name:
            students = students.filter(last_name_lower__contains=search_last_name.lower())
        return students

tutoringApp/tutors/views/availability_api.py
"""Endpoints for interacting with models from `Tutors` app."""
from django.http import HttpRequest
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView

from tutors.models import Availability
from tutors.serializers import AvailabilitySerializer


class AvailabilityAPIView(APIView):
    """API for interacting with models from `Tutors` app."""

    def delete(self, _request: HttpRequest, pk: int) -> Response:
        """Delete the Availability object with a provided PK.

        The view checks if an object with provided primary key
        exists before attempting to fetch and delete it. If it
        does not exist, an appropriate message is returned.

        Args:
            request: Instance of the HttpRequest class containing
                    every information about the request sent to the
                    server.
            pk: Primary key of the `Availability` object that is meant
                to be deleted.
        Returns:
            Instance of the `Response` class with an appropraite
            status code.
        """
        try:
            availability = Availability.objects.get(pk=pk)
        except Availability.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        availability.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    def post(self, request: HttpRequest) -> Response:
        """Create new instance of the `Availability` model.

        The new instance of the model is created based on the
        data sent in the request.

        Args:
            request: Instance of the HttpRequest class containing
                    every information about the request sent to the
                    server, includign that of new `Availability` object
                    that is about to be created.
        Returns:
            Instance of the `Response` class with an appropraite
            status code and or data about newly created `Availability`
            instance.
        """
        availability_serializer = AvailabilitySerializer(data=request.data)
        if availability_serializer.is_valid():
            availability_serializer.save()
            return Response(availability_serializer.data)
        return Response(
            availability_serializer.errors, status=status.HTTP_400_BAD_REQUEST
        )

    def put(self, request: HttpRequest) -> Response:
        """Updates existing instance of the `Availability` model.

        The instance is updated based on the data sent in the
        request.

        Args:
            request: Instance of the HttpRequest class containing
                    every information about the request sent to the
                    server, includign that of which `Availability`
                    object should be updated and in what way.
        Returns:
            Instance of the `Response` class with an appropraite
            status code and or data about newly updated `Availability`
            object.
        """
        availability_serializer = AvailabilitySerializer(data=request.data)
        if availability_serializer.is_valid():
            availability_serializer.save()
            return Response(availability_serializer.data)
        return Response(
            availability_serializer.errors, status=status.HTTP_400_BAD_REQUEST
        )

tutoringApp/tutors/templates/tutors/services.html
{% extends 'tutoringApp/base_tutor.html' %}

{% load profiles_extras %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'tutors\css\services.css' %}">
{% endblock %}

{% block script %}
{% load static %}
    <script defer src="{% static 'profiles/js/FormsetHandler.js' %}"></script>
    <script defer src="{% static 'tutors/js/ServiceConfigurationHandler.js' %}"></script>
{% endblock %}

{% block main %}
<div class="stack-container">
    <div class="navigation link-container">
        <div class="navigation-link info-top">
            <a href="{% url 'profiles:tutor_display' object.pk %}">
                Go back to profile
            </a>
        </div>
    </div>
    <div class="services box">
        <div class="services-header box-header">
            Your services
        </div>
        <div class="services-main box-main_padded">
            <form method="POST">
                {% csrf_token %}
                <div class="services-main-list box-main_padded">
                    <div class="services-main-list-management_form hidden">
                        {{ service_formset.management_form }}
                    </div>
                    {% if service_formset_unique_error %}
                        <div class="services-main-list-errors form_error">
                            {{service_formset_unique_error}}
                        </div>
                        {% endif %}
                    {% for service_form in service_formset %}
                        {% if service_form.instance.pk %}
                            <div class="services-main-list-service box box-main_padded">
                                {% for hidden_field in service_form.hidden_fields %}
                                    {{ hidden_field }}
                                {% endfor %}
                                <div class="services-main-list-service-info stack-adjecent-container">
                                    <div class="services-main-list-service-info-subject stack-container_smaller">
                                        <div class="services-main-list-service-info-subject-top info-top">
                                            Subject
                                        </div>
                                        <div class="services-main-list-service-info-subject-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.subject.name %}
                                        </div>
                                        <div class="services-main-list-service-info-subject-bottom info-bottom">
                                            {{ service_form.subject }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-duration stack-container_smaller">
                                        <div class="services-main-list-service-info-duration-top info-top">
                                            Duration
                                        </div>
                                        <div class="services-main-list-service-info-duration-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.session_length.name %}
                                        </div>
                                        <div class="services-main-list-service-info-duration-bottom info-bottom">
                                            {{ service_form.session_length }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-hours stack-container_smaller">
                                        <div class="services-main-list-service-info-hours-top info-top">
                                            No. of hours
                                        </div>
                                        <div class="services-main-list-service-info-hours-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.number_of_hours.name %}
                                        </div>
                                        <div class="services-main-list-service-info-hours-bottom info-bottom">
                                            {{ service_form.number_of_hours }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-price stack-container_smaller">
                                        <div class="services-main-list-service-info-price-top info-top">
                                            Price per hour
                                        </div>
                                        <div class="services-main-list-service-info-price-bottom info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.price_per_hour.name %}
                                        </div>
                                        <div class="services-main-list-service-info-price-bottom info-bottom">
                                            {{ service_form.price_per_hour }} {{currency}}
                                        </div>
                                    </div>

                                </div>

                                {% if not service_form.instance.is_default %}
                                <a href="{% url 'tutors:service_delete' service_form.instance.id %}">
                                    <div class="services-main-list-service-delete icon_green">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                                            <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
                                        </svg>
                                    </div>
                                </a>
                                {% endif %}
                            </div>
                        {% else %}
                            <div class="services-main-list-service services-main-list-service_empty box box-main_padded" id="services-main-list-service_empty-0">
                                {% for hidden_field in service_form.hidden_fields %}
                                    {{ hidden_field }}
                                {% endfor %}
                                <div class="services-main-list-service-info stack-adjecent-container">
                                    <div class="services-main-list-service-info-subject stack-container_smaller">
                                        <div class="services-main-list-service-info-subject-top info-top">
                                            Subject
                                        </div>
                                        <div class="services-main-list-service-info-subject-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.subject.name %}
                                        </div>
                                        <div class="services-main-list-service-info-subject-bottom info-bottom">
                                            {{ service_form.subject }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-duration stack-container_smaller">
                                        <div class="services-main-list-service-info-duration-top info-top">
                                            Duration
                                        </div>
                                        <div class="services-main-list-service-info-duration-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.session_length.name %}
                                        </div>
                                        <div class="services-main-list-service-info-duration-bottom info-bottom">
                                            {{ service_form.session_length }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-hours stack-container_smaller">
                                        <div class="services-main-list-service-info-hours-top info-top">
                                            No. of hours
                                        </div>
                                        <div class="services-main-list-service-info-hours-bottom_errors info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.number_of_hours.name %}
                                        </div>
                                        <div class="services-main-list-service-info-hours-bottom info-bottom">
                                            {{ service_form.number_of_hours }}
                                        </div>
                                    </div>

                                    <div class="services-main-list-service-info-price stack-container_smaller">
                                        <div class="services-main-list-service-info-price-top info-top">
                                            Price per hour
                                        </div>
                                        <div class="services-main-list-service-info-price-bottom info-bottom">
                                            {% formset_error_renderer service_formset_errors forloop.counter0 service_form.price_per_hour.name %}
                                        </div>
                                        <div class="services-main-list-service-info-price-bottom info-bottom">
                                            {{ service_form.price_per_hour }} {{currency}}
                                        </div>
                                    </div>

                                </div>
                                <div class="services-main-list-service-delete services-main-list-service_empty-delete icon_green" id="services-main-list-service-delete-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
                                        <path d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8 2.146 2.854Z"/>
                                    </svg>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}

                    <div class="services-main-list-add add_button">
                        <div class="services-main-list-add-icon add_button-icon">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-plus-lg" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 2a.5.5 0 0 1 .5.5v5h5a.5.5 0 0 1 0 1h-5v5a.5.5 0 0 1-1 0v-5h-5a.5.5 0 0 1 0-1h5v-5A.5.5 0 0 1 8 2Z"/>
                            </svg>
                        </div>
                    </div>

                </div>
                <div class="services-main-submit centered_button_container">
                    <button class="services-main-submit-btn button_fill_green" type="submit">
                        Submit
                    </button>
                </div>
            </form>        
        </div>
    </div>
</div>
{% endblock %}