tutoringApp/chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"
urlpatterns = [
    path("tutor/<int:tutor_id>/", view=views.TutorChatView.as_view(), name="tutor_chat"),
    path("tutor/<int:tutor_id>/<int:student_id>/", view=views.TutorChatWindowView.as_view(), name="tutor_chat_window"),
    path("student/<int:student_id>/", view=views.StudentChatView.as_view(), name="student_chat"),
    path("student/<int:tutor_id>/<int:student_id>/", view=views.StudentChatWindowView.as_view(), name="student_chat_window"),
]

tutoringApp/tutoringApp/urls.py
"""URL configuration for tutoringApp project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("profiles/", include("profiles.urls")),
    path("tutors/", include("tutors.urls")),
    path("lessons/", include("lessons.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    path("search/", include("search.urls")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutoringApp/chat/models.py
from django.db import models

# Create your models here.

tutoringApp/chat/views/chat.py
"""Views for chat-related functionalities."""
from typing import Any

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.list import ListView

from profiles.forms import AccountType
from profiles.models import Profile
from subscriptions.models import Subscription


class StudentChatView(ListView, LoginRequiredMixin):
    """View for displaying available chat partners for Students."""

    model = Profile
    template_name = "chat\chat_student.html"
    context_object_name = "profiles"

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Check if the current user is the intented Student.

        The method checks if the currently logged in user is the Student
        whos PK has been passed as the URL argument.

        Return:
            An instance of the HttpResponse class rendering an
            appropriate redirection page if the current user
            is not the intented Student, otherwise a page with a
            list of Tutors that the user is 'subscribed' to.
        """
        if (
            self.request.session["account_type"] == AccountType.TUTOR.value
            or self.request.user.pk != self.kwargs["student_id"]
        ):
            return render(
                request=self.request,
                template_name="tutoringApp/forbidden.html",
                status=403,
                context={
                    "warning_message": "You are not allowed to access this page.",
                    "redirect_link": reverse("home:home"),
                    "redirect_destination": "home page",
                },
            )
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> list[Profile]:
        """Fetch a list of Tutors that the given Student is 'subscribed' to."""
        return list(
            set(
                [
                    subscription.tutor
                    for subscription in Subscription.objects.filter(
                        student__pk=self.kwargs["student_id"]
                    )
                ]
            )
        )


class TutorChatView(ListView, LoginRequiredMixin):
    """View for displaying available chat partners for Tutors."""

    model = Profile
    template_name = "chat\chat_tutor.html"
    context_object_name = "profiles"

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Check if the current user is the intented Tutor.

        The method checks if the currently logged in user is the Tutor
        whos PK has been passed as the URL argument.

        Return:
            An instance of the HttpResponse class rendering an
            appropriate redirection page if the current user
            is not the intented Tutor, otherwise a page with a
            list of Students that are 'subscribed' to the given Tutor.
        """
        if (
            self.request.session["account_type"] == AccountType.STUDENT.value
            or self.request.user.pk != self.kwargs["tutor_id"]
        ):
            return render(
                request=self.request,
                template_name="tutoringApp/forbidden.html",
                status=403,
                context={
                    "warning_message": "You are not allowed to access this page.",
                    "redirect_link": reverse("home:home"),
                    "redirect_destination": "home page",
                },
            )
        return super().get(request, *args, **kwargs)

    def get_queryset(self) -> list[Profile]:
        """Fetch a list of Students that are 'subscribed' to the given Tutor."""
        return list(
            set(
                [
                    subscription.student
                    for subscription in Subscription.objects.filter(
                        tutor__pk=self.kwargs["tutor_id"]
                    )
                ]
            )
        )


class StudentChatWindowView(StudentChatView):
    """View for displaying available chat partners for Students and the chat window."""

    template_name = "chat\chat_student_window.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Add name of the receiving Tutor to the context."""
        context = super().get_context_data(**kwargs)
        context["tutor"] = Profile.objects.get(pk=self.kwargs["tutor_id"])
        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Check if the given user is the intented Student or Tutor."""
        if self.request.user.pk != self.kwargs["student_id"]:
            return render(
                request=self.request,
                template_name="tutoringApp/forbidden.html",
                status=403,
                context={
                    "warning_message": "You are not allowed to access this page.",
                    "redirect_link": reverse("home:home"),
                    "redirect_destination": "home page",
                },
            )
        return super().get(request, *args, **kwargs)


class TutorChatWindowView(TutorChatView):
    """View for displaying available chat partners for Tutors and the chat window."""

    template_name = "chat\chat_tutor_window.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Add name of the receiving Student to the context."""
        context = super().get_context_data(**kwargs)
        context["student"] = Profile.objects.get(pk=self.kwargs["student_id"])
        return context

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        """Check if the given user is the intented Student or Tutor."""
        if self.request.user.pk != self.kwargs["tutor_id"]:
            return render(
                request=self.request,
                template_name="tutoringApp/forbidden.html",
                status=403,
                context={
                    "warning_message": "You are not allowed to access this page.",
                    "redirect_link": reverse("home:home"),
                    "redirect_destination": "home page",
                },
            )
        return super().get(request, *args, **kwargs)

tutoringApp/chat/templates/chat/chat_student.html
{% extends 'tutoringApp/base_student.html' %}

{% load lesson_extras %}

{% block title %}
    Chat
{% endblock %}

{% block styles %}
{% load static %}
    <link rel="stylesheet" href="{% static 'chat/css/chat.css' %}">
{% endblock %}

{% block main %}
    <div class="chat stack-adjecent-container">
        <div class="chat-left_top box desktop">
            <div class="chat-left_top-header box-header">
                Chats
            </div>
            <div class="chat-left_top-main box-main">
                {% for profile in profiles %}
                    <div class="chat-left_top-main-chat link-container">
                        <a href="{% url 'chat:student_chat_window' profile.pk user.id %}">
                            {{profile.full_name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="chat-left_top box_dropdown mobile">
            <input type="checkbox" class="chat-left_top-checkbox box_dropdown-header-checkbox" id="chat-left_top-checkbox-0">
            <div class="chat-left_top-header box_dropdown-header">
                <div class="chat-left_top-header-text box_dropdown-header-text">
                    Chats
                </div>
                <label for="chat-left_top-checkbox-0">
                    <div class="chat-left_top-header-arrow box_dropdown-header-arrow box_dropdown-header-arrow-down">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                        </svg>
                    </div>

                    <div class="chat-left_top-header-arrow box_dropdown-header-arrow box_dropdown-header-arrow-up">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
                        </svg>
                    </div>
                </label>
            </div>
            <div class="chat-left_top-main box_dropdown-main">
                {% for profile in profiles %}
                    <div class="chat-left_top-main-chat link-container">
                        <a href="{% url 'chat:student_chat_window' profile.pk user.id %}">
                            {{ profile.full_name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="chat-right_bottom box">
            {% block window %}
                <div class="chat-right_bottom-header box-header">
                    Info
                </div>
                <div class="chat-right_bottom-main box-main_padded">
                    Select one of the Tutors to start a chat!
                </div>
            {% endblock %}
        </div>
    </div>
{% endblock %}

tutoringApp/chat/templates/chat/chat_student_window.html
{% extends 'chat/chat_student.html' %}

{% block script %}
{% load static %}
    <script defer src="{% static 'chat/js/chatHandler.js' %}"></script>    
{% endblock %}

{% block window %}
<div class="chat-right_bottom-header box-header">
    {{ tutor.full_name }}
</div>
<div class="chat-right_bottom-main box-main">
    {{ tutor.pk|json_script:"tutor_id" }}
    {{ user.id|json_script:"student_id" }}
    {{ user.id|json_script:"current_user_id"}}
    <div class="chat-right_bottom-main-chat"></div>
    <div class="chat-right_bottom-main-message adjacent-container">
        <div class="chat-right_bottom-main-message-text">
            <textarea id="chat-right_bottom-main-message-text-textarea"></textarea>
        </div>
        <div class="chat-right_bottom-main-message-send icon_green" id="chat-right_bottom-main-message-send-btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-fill" viewBox="0 0 16 16">
                <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z"/>
            </svg>
        </div>
    </div>
</div>
{% endblock %}

tutoringApp/chat/templates/chat/chat_tutor.html
{% extends 'tutoringApp/base_tutor.html' %}

{% load lesson_extras %}

{% block title %}
    Chat
{% endblock %}

{% block styles %}
{% load static %}
    <link rel="stylesheet" href="{% static 'chat/css/chat.css' %}">
{% endblock %}

{% block main %}
    <div class="chat stack-adjecent-container">
        <div class="chat-left_top box desktop">
            <div class="chat-left_top-header box-header">
                Chats
            </div>
            <div class="chat-left_top-main box-main">
                {% for profile in profiles %}
                    <div class="chat-left_top-main-chat link-container">
                        <a href="{% url 'chat:tutor_chat_window' user.id profile.pk %}">
                            {{ profile.full_name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="chat-left_top box_dropdown mobile">
            <input type="checkbox" class="chat-left_top-checkbox box_dropdown-header-checkbox" id="chat-left_top-checkbox-0">
            <div class="chat-left_top-header box_dropdown-header">
                
                <div class="chat-left_top-header-text box_dropdown-header-text">
                    Chats
                </div>
                <label for="chat-left_top-checkbox-0">
                    <div class="chat-left_top-header-arrow box_dropdown-header-arrow box_dropdown-header-arrow-down">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
                        </svg>
                    </div>

                    <div class="chat-left_top-header-arrow box_dropdown-header-arrow box_dropdown-header-arrow-up">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-up" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M7.646 4.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1-.708.708L8 5.707l-5.646 5.647a.5.5 0 0 1-.708-.708l6-6z"/>
                        </svg>
                    </div>

                </label>
            </div>
            <div class="chat-left_top-main box_dropdown-main">
                {% for profile in profiles %}
                    <div class="chat-left_top-main-chat link-container">
                        <a href="{% url 'chat:tutor_chat_window' user.id profile.pk %}">
                            {{ profile.full_name}}
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="chat-right_bottom box">
            {% block window %}
                <div class="chat-right_bottom-header box-header">
                    Info
                </div>
                <div class="chat-right_bottom-main box-main_padded">
                    Select one of the Students to start a chat!
                </div>
            {% endblock %}
        </div>
    </div>
{% endblock %}

tutoringApp/chat/templates/chat/chat_tutor_window.html
{% extends 'chat/chat_tutor.html' %}



{% block script %}
{% load static %}
    <script defer src="{% static 'chat/js/chatHandler.js' %}"></script>    
{% endblock %}

{% block window %}
<div class="chat-right_bottom-header box-header">
    {{ student.full_name }}
</div>
<div class="chat-right_bottom-main box-main">
    {{ user.id|json_script:"tutor_id" }}
    {{ student.pk|json_script:"student_id" }}
    {{ user.id|json_script:"current_user_id"}}
    <div class="chat-right_bottom-main-chat"></div>
    <div class="chat-right_bottom-main-message adjacent-container">
        <div class="chat-right_bottom-main-message-text">
            <textarea id="chat-right_bottom-main-message-text-textarea"></textarea>
        </div>
        <div class="chat-right_bottom-main-message-send icon_green" id="chat-right_bottom-main-message-send-btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-send-fill" viewBox="0 0 16 16">
                <path d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z"/>
            </svg>
        </div>
    </div>
</div>
{% endblock %}