tutoringApp/chat/urls.py
from django.urls import path

from chat import views

app_name = "chat"
urlpatterns = [
    path("tutor/<int:tutor_id>/", view=views.TutorChatView.as_view(), name="tutor_chat"),
    path("tutor/<int:tutor_id>/<int:student_id>/", view=views.TutorChatWindowView.as_view(), name="tutor_chat_window"),
    path("student/<int:student_id>/", view=views.StudentChatView.as_view(), name="student_chat"),
    path("student/<int:tutor_id>/<int:student_id>/", view=views.StudentChatWindowView.as_view(), name="student_chat_window"),
]

tutoringApp/lessons/urls.py
from django.urls import path

from lessons import views

app_name = "lessons"
api_endpoints = [
    path(
        "solution/create",
        view=views.SolutionAPIView.as_view(),
        name="solution_create",
    ),
    path(
        "solution/delete/<int:pk>",
        view=views.SolutionAPIView.as_view(),
        name="solution_delete",
    ),
    path(
        "task/update/<int:pk>",
        view=views.TaskAPIView.as_view(),
        name="task_update",
    ),
    path(
        "absence/update/<int:pk>",
        view=views.update_lesson_absence_view,
        name="lesson_update_absence",
    ),
]
urlpatterns = [
    path(
        "booking/create/<int:availability_id>",
        view=views.create_booking_view,
        name="booking_create",
    ),
    path(
        "booking/display/student",
        view=views.BookingsDisplay4Student.as_view(),
        name="booking_display_student",
    ),
    path(
        "booking/display/tutor",
        view=views.BookingsDisplay4Tutor.as_view(),
        name="booking_display_tutor",
    ),
    path(
        "booking/delete/<int:pk>",
        view=views.BookingDeleteView.as_view(),
        name="booking_delete",
    ),
    path(
        "update/<int:pk>",
        view=views.UpdateLessonView.as_view(),
        name="lesson_update",
    ),
    path(
        "task/delete/<int:task_id>",
        view=views.delete_task_view,
        name="task_delete",
    ),
    path(
        "material/delete/<int:material_id>",
        view=views.delete_material_view,
        name="material_delete",
    ),
    path(
        "student/<int:pk>",
        view=views.DisplayLessonStudentView.as_view(),
        name="lesson_display_student",
    ),
    path(
        "tutor/<int:pk>",
        view=views.DisplayLessonTutorView.as_view(),
        name="lesson_display_tutor",
    ),
] + api_endpoints

tutoringApp/tutoringApp/urls.py
"""URL configuration for tutoringApp project."""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("profiles/", include("profiles.urls")),
    path("tutors/", include("tutors.urls")),
    path("lessons/", include("lessons.urls")),
    path("subscriptions/", include("subscriptions.urls")),
    path("search/", include("search.urls")),
    path("chat/", include("chat.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutoringApp/lessons/forms.py
"""Forms for the lessons app."""
from django import forms

from lessons.models import Booking, Entry, Lesson, Material, Task


class LessonForm(forms.ModelForm):
    """Form for updating Lesson objects."""

    class Meta:
        model = Lesson
        fields = "__all__"

        widgets = {
            "date": forms.DateTimeInput(
                attrs={"type": "datetime-local"},
            )
        }


class BookingForm(forms.ModelForm):
    """Form for creating Booking objects."""

    class Meta:
        model = Booking
        exclude = "__all__"


class TaskForm(forms.ModelForm):
    """Form for creating Task objects."""

    class Meta:
        model = Task
        exclude = ["lesson", "status"]


task_formset = forms.inlineformset_factory(
    parent_model=Lesson,
    model=Task,
    form=TaskForm,
    extra=1,
    can_delete=True,
    can_delete_extra=False,
    min_num=0,
)


class MaterialForm(forms.ModelForm):
    """Form for creating Material objects."""

    class Meta:
        model = Material
        exclude = ["lesson", "upload_date"]


material_formset = forms.inlineformset_factory(
    parent_model=Lesson,
    model=Material,
    form=MaterialForm,
    extra=1,
    can_delete=True,
    can_delete_extra=False,
    min_num=0,
)


class EntryForm(forms.ModelForm):
    """Form for creating Entry objects."""

    class Meta:
        model = Entry
        exclude = ["publish_date", "lesson"]

tutoringApp/lessons/views.py
from django.shortcuts import render

# Create your views here.

tutoringApp/lessons/views/booking.py
"""Views for managin Booking objects."""
from logging import getLogger
from typing import Optional

from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from lessons.models import Booking, Lesson
from profiles.models import Profile
from tutors.models import Availability

LOGGER = getLogger(__name__)


def user_is_tutor_error(
    request: HttpRequest, availability_id: int
) -> Optional[HttpResponse]:
    """Check if the currently logged in user is a Tutor.

    Args:
        request: An instance of the HttpRequest class, containing
                every information about the request sent to the server.
        availability_id: Primary key of the Availability object that the
                Booking will be related to.

    Returns:
        Instance of the HttpResponse class with warning page rendered
        if the currently logged in user is a Tutor, None otherwise.
    """
    profile = Profile.objects.get(user=request.user)
    if not profile.is_student():
        LOGGER.warning(
            "Tutor %(username)s with id %(id)s attempting to book a session under Availabilit with id %()s",
            {
                "username": request.user.username,
                "id": request.user.id,
                "availability_id": availability_id,
            },
        )
        return render(
            request=request,
            template_name="tutoringApp/forbidden.html",
            status=403,
            context={
                "warning_message": "Tutors are not allowed to book sessions with other tutors.",
                "redirect_link": reverse("home:home"),
                "redirect_destination": "home page",
            },
        )


def availability_object_does_not_exist_error(
    request: HttpRequest, availability_id: int
) -> Optional[HttpResponse]:
    """Check if Availability object with provided ID does exist.

    Args:
        request: An instance of the HttpRequest class, containing
                    every information about the request sent to the server.
        availability_id: Primary key of the Availability object that the
                    Booking will be related to.

    Returns:
        Instance of the HttpResponse class with warning page rendered
        if the Availability object with provided ID does not exist,
        None otherwise.
    """
    try:
        Availability.objects.get(pk=availability_id)
    except Availability.DoesNotExist:
        return render(
            request=request,
            template_name="tutoringApp/forbidden.html",
            status=404,
            context={
                "warning_message": "Availability object with provided primary key does not exist.",
                "redirect_link": reverse("home:home"),
                "redirect_destination": "home page",
            },
        )


def booking_relating_to_availability_already_exists_error(
    request: HttpRequest, availability_id: int
) -> Optional[HttpResponse]:
    """Check if a Booking relating to Availability with given ID already exists.

    Args:
        request: An instance of the HttpRequest class, containing
                    every information about the request sent to the server.
        availability_id: Primary key of the Availability object that the
                    Booking would be related to.

    Returns:
        Instance of the HttpResponse class with warning page rendered
        if the Booking realting to given Availability alreasy exists,
        None otherwise.
    """
    availability = Availability.objects.get(pk=availability_id)
    try:
        Booking.objects.get(availability=availability)
        return render(
            request=request,
            template_name="tutoringApp/forbidden.html",
            status=404,
            context={
                "warning_message": "Booking related to Availability with provided ID already exists.",
                "redirect_link": reverse(
                    "profiles:tutor_display",
                    kwargs={"pk": availability.service.tutor.pk},
                ),
                "redirect_destination": "tutor's profile",
            },
        )
    except Booking.DoesNotExist:
        return None


def availability_is_outdated_error(
    request: HttpRequest, availability_id: int
) -> Optional[HttpResponse]:
    """Check if the Availability object with given ID is outdated.

    Args:
        request: An instance of the HttpRequest class, containing
                    every information about the request sent to the server.
        availability_id: Primary key of the Availability object that the
                    Booking would be related to.

    Returns:
        Instance of the HttpResponse class with warning page rendered
        if the given Availability object is outdated, None otherwise.
    """
    availability = Availability.objects.get(pk=availability_id)
    if availability.is_outdated:
        return render(
            request=request,
            template_name="tutoringApp/forbidden.html",
            status=403,
            context={
                "warning_message": "Availability is outdated. Please choose another available time slot.",
                "redirect_link": reverse(
                    "profiles:tutor_display",
                    kwargs={"pk": availability.service.tutor.pk},
                ),
                "redirect_destination": "tutor's profile",
            },
        )


@login_required
def create_booking_view(request: HttpRequest, availability_id: int) -> HttpResponse:
    """Create Booking and corresponding Lesson object.

    The view checks if the request sent is a POST or GET request.
    In case of both request tyoes several checking functions are
    invoked to see if the data and requestor are allowed. If there
    are no errors, different request types result in different behaviors:
        - In case of GET, a confirmation page is displayed.
        - In case of POST, a Booking object is created.

    Args:
        request: An instance of the HttpRequest class, containing
                every information about the request sent to the server.
        availability_id: Primary key of the Availability object that the
                Booking will be related to.

    Returns:
        Instance of the HttpResponse class with rendered warning messages
        in case of errors. If there are no errors, GET request results in
        a response with confirmation page. In case of POST, the Student is
        redirected to their profile page.

    """
    error_checking_functions = [
        user_is_tutor_error,
        availability_object_does_not_exist_error,
        booking_relating_to_availability_already_exists_error,
        availability_is_outdated_error,
    ]
    if request.method == "GET":
        for error_checking_function in error_checking_functions:
            error_res = error_checking_function(request, availability_id)
            if error_res:
                return error_res
        availability = Availability.objects.get(pk=availability_id)
        return render(
            request,
            "booking/create.html",
            context={
                "availability": availability,
                "tutor_profile": reverse(
                    "profiles:tutor_display",
                    kwargs={"pk": availability.service.tutor.pk},
                ),
            },
        )
    elif request.method == "POST":
        for error_checking_function in error_checking_functions:
            error_res = error_checking_function(request, availability_id)
            if error_res:
                return error_res
        lesson = Lesson()
        lesson.save()
        booking = Booking(
            lesson_info=lesson,
            student=Profile.objects.get(user=request.user),
            availability=Availability.objects.get(pk=availability_id),
        )
        booking.save()
        return HttpResponseRedirect(
            reverse("profiles:student_display", kwargs={"pk": request.user.pk})
        )

tutoringApp/lessons/templates/booking/create.html
{% extends 'tutoringApp/base_student.html' %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/create.css' %}">
{% endblock %}

{% block main %}
    <div class="confirm box">
        <div class="confirm-header box-header">
            Confirmation
        </div>
        <div class="confirm-main box-main_padded stack_container">
            <div class="confirm-main-message">
                Do you want to confirm the booking?
            </div>
            <div class="confirm-main-btns centered_button_container adjacent-container">
                <form method="post" class="confirm-main-btns-form">
                    {% csrf_token %}
                    <button type="submit" class="confirm-main-btns-form-btn button_fill_green">
                        Confirm
                    </button>
                </form>
                <form action="{{ tutor_profile }}">
                    {% csrf_token %}
                    <button type="submit" class="confirm-main-btns-btn button_fill_red">
                        Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tutoringApp/lessons/templates/booking/delete.html
{% extends 'tutoringApp/base_student.html' %}

{% block title %}
    Delete Booking
{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/delete.css' %}">
{% endblock %}

{% block main %}
    <div class="confirm box">
        <div class="confirm-header box-header">
            Confirmation
        </div>
        <div class="confirm-main box-main_padded stack_container">
            <div class="confirm-main-message">
                Do you want to delete the booking?
            </div>
            <div class="confirm-main-btns centered_button_container adjacent-container">
                <form method="post" class="confirm-main-btns-form">
                    {% csrf_token %}
                    {{form}}
                    <button type="submit" class="confirm-main-btns-form-btn button_fill_green">
                        Confirm
                    </button>
                </form>
                <form action="{% url 'lessons:booking_display_student' %}">
                    {% csrf_token %}
                    <button type="submit" class="confirm-main-btns-btn button_fill_red">
                        Cancel
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tutoringApp/lessons/templates/booking/display.html
{% load booking_extras %}

{% block script %}
    {% load static %}
    <script defer src="{% static 'booking/js/DisplayController.js' %}"></script>
{% endblock %}

<div class="sessions stack-container">
    <div class="sessions-filters stack-adjecent-container">
        <div class="sessions-filters-filter">
            <div class="sessions-filters-filter-label info-top">
                {% if is_student %}
                    Tutor
                {% else %}
                    Student
                {% endif %}
            </div>
            <div class="sessions-filters-filter-input">
                <select class="sessions-filter-tutor options" id="sessions-filter-profile">
                    <option></option>
                    {% for profile_filter in profile_filter_list %}
                        <option value="{{profile_filter.user.id}}">{{profile_filter.user.username}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="sessions-filters-filter">
            <div class="sessions-filters-filter-label info-top">
                From
            </div>
            <div class="sessions-filters-filter-input">
                <input class="sessions-filter-from date-input" type="date" id="sessions-filter-from">
            </div>
        </div>
        <div class="sessions-filters-filter">
            <div class="sessions-filters-filter-label info-top">
                To
            </div>
            <div class="sessions-filters-filter-input">
                <input class="sessions-filter-to date-input" type="date" id="sessions-filter-to">
            </div>            
        </div>
        <div class="sessions-filters-btn_filter button_fill_green" id="sessions-filters-btn_filter">
            <a href="#" class="sessions-filters-btn_filter-link" id="sessions-filters-btn_filter-link">
                Filter
            </a>
        </div>
        <div class="sessions-filters-btn_clear button_fill_green" id="sessions-filters-btn_clear">
            {% if is_student %}
                <a href="{% url 'lessons:booking_display_student' %}">
                    Clear filter
                </a>
            {% else %}
                <a href="{% url 'lessons:booking_display_tutor' %}">
                    Clear filter
                </a>
            {% endif %}
        </div>
    </div>
    <div class="sessions-list box">
        <div class="sessions-list-header box-header">
            Sessions
        </div>
        <div class="sessions-list-main box-main_padded">
            {% for booking in page_obj %}
                <div class="sessions-list-main-session box box-main_padded stack-adjecent-container">
                    <div class="sessions-list-main-session-left_top">
                        <div class="sessions-list-main-session-left_top-tutor link-container">
                            {% if is_student %}
                                <a href="{% url 'lessons:lesson_display_student' booking.lesson_info.id %}">
                                    {% render_booking_title booking is_student %}
                                </a>
                            {% else %}
                                <a href="{% url 'lessons:lesson_display_tutor' booking.lesson_info.id %}">
                                    {% render_booking_title booking is_student %}
                                </a>
                            {% endif %}
                        </div>
                        <div class="sessions-list-main-session-left_top-time info-bottom">
                            {% render_availability_time_slot booking.availability %}
                        </div>
                        <div class="sessions-list-main-session-left_top-subject info-top">
                            {{ booking.availability.service.subject }}
                        </div>
                    </div>
                    <div class="sessions-list-main-session-right_bottom">
                        {% if is_student and not booking.availability.is_outdated %}
                            <div class="sessions-list-main-session-right_bottom-cancel button_fill_red">
                                <a href="{% url 'lessons:booking_delete' booking.id %}">
                                    Cancel
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
            <div class="sessions-list-main-pagination adjacent-container_small centered_button_container">
                {% if page_obj.has_previous %}
                    <div class="sessions-list-main-pagination-arrow_left icon_green">
                        <a href="?page=1">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </div>
                    <div class="sessions-list-main-pagination-start icon_green">
                        <a href="?page={{ page_obj.previous_page_number }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-double-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8.354 1.646a.5.5 0 0 1 0 .708L2.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                                <path fill-rule="evenodd" d="M12.354 1.646a.5.5 0 0 1 0 .708L6.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </div>
                {% endif %}
                <div class="sessions-list-main-pagination-pages info-top">
                    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </div>
                {% if page_obj.has_next %}
                    <div class="sessions-list-main-pagination-arrow_end icon_green">
                        <a href="?page={{ page_obj.next_page_number }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-double-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M3.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L9.293 8 3.646 2.354a.5.5 0 0 1 0-.708z"/>
                                <path fill-rule="evenodd" d="M7.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L13.293 8 7.646 2.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </a>
                    </div>
                    <div class="sessions-list-main-pagination-arrow_right icon_green">
                        <a href="?page={{ page_obj.paginator.num_pages }}">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

tutoringApp/lessons/templates/booking/display_4_student.html
{% extends 'tutoringApp/base_student.html' %}

{% block title %}
    Booked sessions
{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/display.css' %}">
{% endblock %}

{% block main %}
    {% include 'booking/display.html' %}
{% endblock %}

tutoringApp/lessons/templates/booking/display_4_tutor.html
{% extends 'tutoringApp/base_tutor.html' %}

{% block title %}
    Booked sessions
{% endblock %}

{% block styles %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'booking/css/display.css' %}">
{% endblock %}

{% block main %}
    {% include 'booking/display.html' %}
{% endblock %}